---
title: "Hospital Simulation"
author: "Suraj Nath"
date: "10 April 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Hospital Simulation

```{r}
library(parallel)
library(simmer)
library(simmer.plot)

SIM_TIME <- 80
```

```{r}
patient <- trajectory("patients' path") %>%
  ## add an intake activity 
  seize("nurse", 1) %>%
  timeout(function() rnorm(1, 15)) %>%
  release("nurse", 1) %>%
  ## add a consultation activity
  seize("doctor", 1) %>%
  timeout(function() rnorm(1, 20)) %>%
  release("doctor", 1) %>%
  ## add a planning activity
  seize("administration", 1) %>%
  timeout(function() rnorm(1, 5)) %>%
  release("administration", 1)

envs <- mclapply(1:100, function(i) {
  simmer("SuperDuperSim") %>%
    add_resource("nurse", 1) %>%
    add_resource("doctor", 2) %>%
    add_resource("administration", 1) %>%
    add_generator("patient", patient, function() rnorm(1, 10, 2)) %>%
    run(SIM_TIME) %>%
    wrap()
})
```

# Plot Things

```{r}
plot(envs, what = "resources", metric = "usage", c("nurse", "doctor","administration"))
plot(envs, what = "resources", metric = "utilization", c("nurse", "doctor","administration"))
plot(envs, what = "arrivals", metric = "activity_time")
plot(envs, what = "arrivals", metric = "waiting_time")
plot(envs, what = "arrivals", metric = "flow_time")
```
